# Generated by Django 4.2.2 on 2023-07-27 14:09

from django.db import migrations, models
import sudoku_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SudokuBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.JSONField(default=sudoku_app.models.default_board)),
                ('answer', models.JSONField(default=sudoku_app.models.default_board)),
            ],
        ),
        migrations.DeleteModel(
            name='React',
        ),
    ]
